#!/bin/bash
# Script written by James Garijo-Garde on 5/21/2018
# Opens the subl Command Prompt tool for Windows from within Bash for Ubuntu for Windows 10

if [ $# -gt 0 ]; then
   result=
   for i in "$@"; do
       result="$result $i"
   done
   /mnt/c/"Program Files"/"Sublime Text 3"/subl.exe $result
else
   /mnt/c/"Program Files"/"Sublime Text 3"/subl.exe
fi
